name: CB Workflow

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  cb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          cd cb
          python -m pip install --upgrade pip setuptools wheel pytest pdoc
          python -m pip install torch==2.1.1
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          cd cb
          python -m pytest .

      - name: Build documentation
        run: |
          cd cb
          rm -rf _docs
          mkdir _docs
          python -m pdoc -d google -o _docs/ agent

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cb/_docs
          destination_dir: cb
